# Generated by Django 3.0.4 on 2020-04-03 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abc_app', '0003_choice_gradedquiz_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradedquiz',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='order',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.AddField(
            model_name='gradedquiz',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abc_app.Quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='Quiz Title', max_length=100),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('order', models.SmallIntegerField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='abc_app.Choice')),
                ('choices', models.ManyToManyField(to='abc_app.Choice')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abc_app.Quiz')),
            ],
        ),
    ]
